### PR TITLE
Add Avatar + Friend Code

### LINKED ISSUE #102: Add Avatar + Friend Code to RPC
Display user's avatar in the `small image` section of RPC.
Display user's name and (optionally) friend code in the `small text` section of RPC.

### PR DESCRIPTION
**Pull request by DillonB07**
This PR would close #102.

I've added a section to the settings page that has a friend code option.

Settings page

RPC #1

RPC #2

### CODE REVIEW

**Comment by DillonB07** [comment]
This is a draft PR because there's a major bug with it that if you close the app, it will crash when attempting to re-open it.

**Comment by HotaruBlaze** [comment]
👎

This breaks a bunch of the formatting rules that are enforced by autopep8 that should have been forced before committing via pre-commit,

**Comment by HotaruBlaze** [comment]
I've made some notes about issues I saw with the PR though the mess of formatting changes, I'd still like you to try and fix the formatting issues and repush the commit using pre-commit.

The rules we specifically avoid are E251 and E501, due to it making the code look worse and a lot messier, If you used a formatter or IDE with autoformatting, it ignored `pyproject.toml` in the repo, as well as the commit **should** have failed due to pre-commit not being available , as this is a git pre-commit hook.

**Comment by HotaruBlaze** [comment]
Another thing I just noticed, you should be using the development branch and not the main branch.

**Comment by MCMi460** [comment]
#102 has been added in b024535ef96590715f0dd49b67d0b861f5733faf

**Comment by DillonB07** [comment]
Hmm @HotaruBlaze - No idea why the git pre-commit didn't run. Sorry about using the wrong branch & formatter, but there is no contributing guide, so I didn't know about that.

Also, when I was writing the code, I didn't even think there *was* a formatter as it seemed really messy and honestly quite unreadable.

Thanks for adding the feature @MCMi460

**Pull request closed without merging**
